spring :
  application :
   name : ANGERSERVER
    
    
server :
  port : 8761
  
eureka :

  instance :

    hostname : localhost

  client :
    healthcheck:      enabled: false

    register-with-eureka : false

    fetch-registry : false

  server :

    enable-self-preservation : false
  
  
  
  
     
  